-- 用户评价表
DROP TABLE IF EXISTS `feedback`;
CREATE TABLE `feedback` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `feedback_id` VARCHAR(50) NOT NULL COMMENT '评价ID（UUID）',
    `user_id` BIGINT NOT NULL COMMENT '用户ID',
    `username` VARCHAR(50) NOT NULL COMMENT '用户名',
    `message_id` VARCHAR(50) NOT NULL COMMENT '消息ID',
    `session_id` VARCHAR(50) NOT NULL COMMENT '会话ID',
    `type` TINYINT NOT NULL DEFAULT 1 COMMENT '评价类型：1-满意，2-不满意，3-一般',
    `score` TINYINT NOT NULL DEFAULT 5 COMMENT '评分（1-5星）',
    `content` TEXT COMMENT '评价内容',
    `tags` TEXT COMMENT '标签（JSON格式）',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态：1-已提交，2-已处理，3-已忽略',
    `handler` VARCHAR(50) COMMENT '处理人',
    `handle_time` DATETIME COMMENT '处理时间',
    `handle_result` TEXT COMMENT '处理结果',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_feedback_id` (`feedback_id`),
    UNIQUE KEY `uk_message_id` (`message_id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_session_id` (`session_id`),
    KEY `idx_type` (`type`),
    KEY `idx_score` (`score`),
    KEY `idx_status` (`status`),
    KEY `idx_create_time` (`create_time`),
    KEY `idx_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户评价表';
