-- 风险预警表
DROP TABLE IF EXISTS `risk_alert`;
CREATE TABLE `risk_alert` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `alert_id` VARCHAR(50) NOT NULL COMMENT '预警ID（UUID）',
    `user_id` BIGINT NOT NULL COMMENT '用户ID',
    `username` VARCHAR(50) NOT NULL COMMENT '用户名',
    `alert_type` TINYINT NOT NULL DEFAULT 4 COMMENT '预警类型：1-行为风险预警，2-设备风险预警，3-社交风险预警，4-综合风险预警',
    `risk_level` TINYINT NOT NULL DEFAULT 1 COMMENT '风险等级：1-低风险，2-中风险，3-高风险，4-极高风险',
    `alert_title` VARCHAR(200) COMMENT '预警标题',
    `alert_content` TEXT COMMENT '预警内容',
    `alert_details` TEXT COMMENT '预警详情（JSON格式）',
    `notification_method` TINYINT NOT NULL DEFAULT 4 COMMENT '通知方式：1-WebSocket，2-短信，3-邮件，4-全部',
    `web_socket_status` TINYINT NOT NULL DEFAULT 3 COMMENT 'WebSocket状态：1-已推送，2-推送失败，3-未推送',
    `sms_status` TINYINT NOT NULL DEFAULT 3 COMMENT '短信状态：1-已发送，2-发送失败，3-未发送',
    `email_status` TINYINT NOT NULL DEFAULT 3 COMMENT '邮件状态：1-已发送，2-发送失败，3-未发送',
    `phone_number` VARCHAR(20) COMMENT '接收人手机号',
    `email` VARCHAR(100) COMMENT '接收人邮箱',
    `alert_time` DATETIME NOT NULL COMMENT '预警时间',
    `status` TINYINT NOT NULL DEFAULT 2 COMMENT '状态：1-已处理，2-处理中，3-处理失败',
    `description` VARCHAR(255) COMMENT '描述',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_alert_id` (`alert_id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_alert_type` (`alert_type`),
    KEY `idx_risk_level` (`risk_level`),
    KEY `idx_notification_method` (`notification_method`),
    KEY `idx_alert_time` (`alert_time`),
    KEY `idx_status` (`status`),
    KEY `idx_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='风险预警表';
