-- 社交风险表
DROP TABLE IF EXISTS `social_risk`;
CREATE TABLE `social_risk` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `risk_id` VARCHAR(50) NOT NULL COMMENT '风险ID（UUID）',
    `user_id` BIGINT NOT NULL COMMENT '用户ID',
    `username` VARCHAR(50) NOT NULL COMMENT '用户名',
    `social_type` TINYINT NOT NULL DEFAULT 4 COMMENT '社交类型：1-好友关系，2-群组关系，3-关注关系，4-其他',
    `target_user_id` VARCHAR(50) COMMENT '社交对象ID',
    `target_username` VARCHAR(50) COMMENT '社交对象名称',
    `social_strength` DOUBLE DEFAULT 0 COMMENT '社交关系强度（0-1）',
    `social_content` TEXT COMMENT '社交内容（JSON格式）',
    `social_time` DATETIME COMMENT '社交时间',
    `risk_score` DOUBLE DEFAULT 0 COMMENT '风险分数（0-100）',
    `risk_level` TINYINT NOT NULL DEFAULT 1 COMMENT '风险等级：1-低风险，2-中风险，3-高风险，4-极高风险',
    `risk_details` TEXT COMMENT '风险详情（JSON格式）',
    `status` TINYINT NOT NULL DEFAULT 2 COMMENT '状态：1-已分析，2-分析中，3-分析失败',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_risk_id` (`risk_id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_social_type` (`social_type`),
    KEY `idx_target_user_id` (`target_user_id`),
    KEY `idx_social_time` (`social_time`),
    KEY `idx_risk_level` (`risk_level`),
    KEY `idx_status` (`status`),
    KEY `idx_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='社交风险表';
